### ISSUE TITLE
Updating isn't possible with empty sd card

### ISSUE THREAD

**Issue by sn0ren** [portapack-mayhem/MayhemHub#53] opened 2024-02-24 22:14 UTC
Trying to update the firmware when having a clean freshly formatted SD card in the device isn't possible, as it errors out when the firmware folder doesn't exist.

**Comment by jLynx** [comment] 2024-02-24 22:22
Can replicate. I'll create a fix. The issue is because currently we don't mkdir. So adding that will fix it. Will start on this shortly

**Comment by jLynx** [comment] 2024-02-25 03:29
This is fixed on the website side in this PR https://github.com/portapack-mayhem/MayhemHub/commit/1ea4f9c44c910fbf55286e68e74de6418d26a17a

But there is a bug on the firmware side that is stopping this fix from working. Once https://github.com/portapack-mayhem/mayhem-firmware/pull/1933 gets merged in, then it will work on nightlys from then onwards. 

Any stables or nightlys from before this, you will just have to manually make sure you have a `/FIRMWARE` folder on your SD card

**Closed by jLynx** 2024-02-25 03:29 UTC
Labels: bug
