### ISSUE TITLE
hackrf.app firmware update on MacOS does not work

### ISSUE THREAD

**Issue by pgiacalo** [portapack-mayhem/MayhemHub#69] opened 2024-07-27 01:11 UTC
The Firmware update at the hackrf.app website does not work when using a Macbook. I have v2.0.0 installed on the portapack. I am able to successfully connect to the portapack but when I click the "Update to latest stable release" button nothing appears to happen. 

I am running macOS 12.7.3 on a MacBook Pro (16-inch, 2019).

**Comment by htotoo** [comment] 2024-07-27 07:45
Duplicate of #43 , please track the issue there.

**Closed by htotoo** 2024-07-27 07:45 UTC
